const countries = {
    "am-ET": "Tiếng Amharic",
    "ar-SA": "Tiếng Ả Rập",
    "be-BY": "Tiếng Belarus",
    "bem-ZM": "Tiếng Bemba",
    "bi-VU": "Tiếng Bislama",
    "bjs-BB": "Tiếng Bajan",
    "bn-IN": "Tiếng Bengali",
    "bo-CN": "Tiếng Tây Tạng",
    "br-FR": "Tiếng Breton",
    "bs-BA": "Tiếng Bosnia",
    "ca-ES": "Tiếng Catalan",
    "cop-EG": "Tiếng Coptic",
    "cs-CZ": "Tiếng Séc",
    "cy-GB": "Tiếng Wales",
    "da-DK": "Tiếng Đan Mạch",
    "dz-BT": "Tiếng Dzongkha",
    "de-DE": "Tiếng Đức",
    "dv-MV": "Tiếng Maldives",
    "el-GR": "Tiếng Hy lạp",
    "en-GB": "Tiếng Anh",
    "es-ES": "Tiếng Tây Ban Nha",
    "et-EE": "Tiếng Estonia",
    "eu-ES": "Tiếng Basque",
    "fa-IR": "Tiếng Ba Tư",
    "fi-FI": "Tiếng Phần Lan",
    "fn-FNG": "Tiếng Fanagalo",
    "fo-FO": "Tiếng Faroe",
    "fr-FR": "Tiếng Pháp",
    "gl-ES": "Tiếng Galicia",
    "gu-IN": "Tiếng Gujarati",
    "ha-NE": "Tiếng Hausa",
    "he-IL": "Tiếng Do Thái",
    "hi-IN": "Tiếng Ấn Độ",
    "hr-HR": "Tiếng Croatia",
    "hu-HU": "Tiếng Hungary",
    "id-ID": "Tiếng Indonesia",
    "is-IS": "Tiếng Iceland",
    "it-IT": "Tiếng Ý",
    "ja-JP": "Tiếng Nhật",
    "kk-KZ": "Tiếng Kazakh",
    "km-KM": "Tiếng Khmer(Campuchia)",
    "kn-IN": "Tiếng Kannada(Ấn Độ)",
    "ko-KR": "Tiếng Hàn",
    "ku-TR": "Tiếng Kurd",
    "ky-KG": "Tiếng Kyrgyz",
    "la-VA": "Tiếng La-tinh",
    "lo-LA": "Tiếng Lào",
    "lv-LV": "Tiếng Latvia",
    "men-SL": "Tiếng Mende",
    "mg-MG": "Tiếng Malagasy(Madagascar)",
    "mi-NZ": "Tiếng Maori",
    "ms-MY": "Tiếng Mã Lai",
    "mt-MT": "Tiếng Malta",
    "my-MM": "Tiếng Miến Điện",
    "ne-NP": "Tiếng Nepal",
    "niu-NU": "Tiếng Niue",
    "nl-NL": "Tiếng Hà Lan",
    "no-NO": "Tiếng Na Uy",
    "ny-MW": "Tiếng Chewa",
    "ur-PK": "Tiếng Pakistan",
    "pau-PW": "Tiếng Palau",
    "pa-IN": "Tiếng Punjab",
    "ps-PK": "Tiếng Pashto",
    "pis-SB": "Tiếng Pijin",
    "pl-PL": "Tiếng Ba Lan",
    "pt-PT": "Tiếng Bồ Đào Nha",
    "rn-BI": "Tiếng Kirundi",
    "ro-RO": "Tiếng Roma(La Mã)",
    "ru-RU": "Tiếng Nga",
    "sg-CF": "Tiếng Sango",
    "si-LK": "Tiếng Sinhala(Sri Lanka)",
    "sk-SK": "Tiếng Slovak",
    "sm-WS": "Tiếng Samoa",
    "sn-ZW": "Tiếng Shona(Zimbabwe)",
    "so-SO": "Tiếng Somali",
    "sq-AL": "Tiếng Albania",
    "sr-RS": "Tiếng Séc-bia",
    "sv-SE": "Tiếng Thụy Điển",
    "sw-SZ": "Tiếng Swahili",
    "ta-LK": "Tiếng Tamil(Sri Lanka/Singapore)",
    "te-IN": "Tiếng Telugu",
    "tet-TL": "Tiếng Tetum(Đông Timor/Tây Timor)",
    "tg-TJ": "Tiếng Tajik",
    "th-TH": "Tiếng Thái",
    "ti-TI": "Tiếng Tigrinya(Bắc Ethiopia)",
    "tk-TM": "Tiếng Turkmen(Turkmenistan)",
    "tl-PH": "Tiếng Tagalog",
    "tn-BW": "Tiếng Tswana(Nam Phi)",
    "to-TO": "Tiếng Tongan",
    "tr-TR": "Tiếng Thổ Nhĩ Kỳ",
    "uk-UA": "Tiếng Ukraina",
    "uz-UZ": "Tiếng Uzbek(Uzbekistan)",
    "vi-VN": "Tiếng Việt",
    "wo-SN": "Tiếng Wolof",
    "xh-ZA": "Tiếng Xhosa(Nam Phi)",
    "yi-YD": "Tiếng Yiddish(Đức/Do Thái)",
    "zu-ZA": "Tiếng Zulu"
}